import { pool } from "../storage/postgres.client";

type Db = Pick<typeof pool,"query">;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const uuid=(value:unknown,name:string)=>{const result=String(value??"");if(!UUID.test(result))throw Object.assign(new Error(`${name} is invalid`),{statusCode:400,code:"invalid_reference"});return result;};
const text=(value:unknown,name:string,max=200)=>{const result=String(value??"").trim();if(!result||result.length>max)throw Object.assign(new Error(`${name} is required`),{statusCode:400,code:"invalid_field"});return result;};

export const listDevices=async(db:Db=pool)=>(await db.query(`SELECT * FROM textile_lab.devices ORDER BY created_at`)).rows;
export const listSpecimens=async(db:Db=pool)=>(await db.query(`SELECT * FROM textile_lab.specimens ORDER BY specimen_identifier`)).rows;
export const listSessions=async(db:Db=pool)=>(await db.query(`SELECT s.*,d.display_name AS device_name,p.display_name AS specimen_name FROM textile_lab.test_sessions s JOIN textile_lab.devices d ON d.id=s.device_id JOIN textile_lab.specimens p ON p.id=s.specimen_id ORDER BY s.started_at DESC LIMIT 50`)).rows;
export const listChannels=async(db:Db=pool)=>(await db.query(`SELECT c.*,d.device_identifier,a.adapter_identifier,a.adapter_version,a.transport FROM textile_lab.channels c JOIN textile_lab.devices d ON d.id=c.device_id LEFT JOIN textile_lab.adapter_definitions a ON a.id=c.adapter_definition_id WHERE c.active=true ORDER BY c.created_at`)).rows;
export const listProtocols=async(db:Db=pool)=>(await db.query(`SELECT p.*,c.channel_identifier FROM textile_lab.experiment_protocols p LEFT JOIN textile_lab.channels c ON c.id=p.channel_id ORDER BY p.created_at DESC`)).rows;
export const listCalibrationRuns=async(db:Db=pool)=>(await db.query(`SELECT cr.*,p.protocol_identifier,p.version AS protocol_version,c.channel_identifier,d.device_identifier,s.specimen_identifier FROM textile_lab.calibration_runs cr JOIN textile_lab.experiment_protocols p ON p.id=cr.protocol_id JOIN textile_lab.channels c ON c.id=cr.channel_id JOIN textile_lab.devices d ON d.id=cr.device_id JOIN textile_lab.specimens s ON s.id=cr.specimen_id ORDER BY cr.created_at DESC`)).rows;
export const listDerivedResults=async(db:Db=pool)=>(await db.query(`SELECT dr.*,a.algorithm_identifier,a.version AS algorithm_version,COALESCE((SELECT rr.to_state FROM textile_lab.result_reviews rr WHERE rr.derived_result_id=dr.id AND rr.decision='approved' ORDER BY rr.reviewed_at DESC,rr.id DESC LIMIT 1),dr.maturity_state) AS canonical_maturity_state FROM textile_lab.derived_results dr JOIN textile_lab.algorithm_versions a ON a.id=dr.algorithm_version_id ORDER BY dr.created_at DESC`)).rows;
export async function createChannel(input:Record<string,unknown>,actor:string,db:Db=pool){const result=await db.query(`INSERT INTO textile_lab.channels(device_id,adapter_definition_id,channel_identifier,display_name,raw_data_type,unit,scale_metadata,signal_stage,version,hardware_revision_snapshot,firmware_version_snapshot,created_by) SELECT d.id,$2,$3,$4,$5,$6,$7,'raw',$8,d.hardware_revision,d.firmware_version,$9 FROM textile_lab.devices d WHERE d.id=$1 RETURNING *`,[uuid(input.device_id,"device_id"),input.adapter_definition_id?uuid(input.adapter_definition_id,"adapter_definition_id"):null,text(input.channel_identifier,"channel_identifier"),text(input.display_name,"display_name"),text(input.raw_data_type,"raw_data_type"),input.unit?text(input.unit,"unit"):null,json(input.scale_metadata,{}),positiveInteger(input.version??1,"version"),actor]);if(!result.rows[0])throw Object.assign(new Error("Device not found"),{statusCode:404,code:"device_not_found"});return result.rows[0];}

export async function overview(db:Db=pool){
  const result=await db.query(`SELECT
    (SELECT row_to_json(d) FROM textile_lab.devices d ORDER BY (d.status='connected') DESC,d.last_connected_at DESC NULLS LAST LIMIT 1) AS device,
    (SELECT row_to_json(p) FROM textile_lab.specimens p WHERE p.status IN('active','testing') ORDER BY (p.status='testing') DESC,p.created_at LIMIT 1) AS specimen,
    (SELECT row_to_json(s) FROM textile_lab.test_sessions s WHERE s.status='active' ORDER BY s.started_at DESC LIMIT 1) AS session,
    (SELECT row_to_json(r) FROM textile_lab.raw_readings r ORDER BY r.received_at DESC,r.id DESC LIMIT 1) AS latest_reading`);
  return result.rows[0];
}

export async function registerDevice(input:Record<string,unknown>,actor:string,db:Db=pool){
  const values=[text(input.device_identifier,"device_identifier"),text(input.display_name,"display_name"),text(input.hardware_type,"hardware_type"),text(input.hardware_model,"hardware_model"),input.firmware_version?text(input.firmware_version,"firmware_version"):null,text(input.transport,"transport"),actor];
  const result=await db.query(`INSERT INTO textile_lab.devices(device_identifier,display_name,hardware_type,hardware_model,firmware_version,transport,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7)
    ON CONFLICT(device_identifier) DO UPDATE SET display_name=EXCLUDED.display_name,hardware_type=EXCLUDED.hardware_type,hardware_model=EXCLUDED.hardware_model,firmware_version=EXCLUDED.firmware_version,transport=EXCLUDED.transport,updated_at=now(),updated_by=EXCLUDED.updated_by
    RETURNING *`,values);return result.rows[0];
}

export async function startTestSession(input:Record<string,unknown>,actor:string,db:Db=pool){
  const result=await db.query(`INSERT INTO textile_lab.test_sessions(specimen_id,device_id,test_user_id,activity_purpose,analytics_population_snapshot,analytics_eligible,protocol_identifier,protocol_version,notes,created_by) SELECT $1,$2,$3,$4,p.analytics_population,false,$5,$6,$7,$8 FROM (SELECT $3::uuid AS id) requested LEFT JOIN lema.user_profiles p ON p.id=requested.id RETURNING *`,[uuid(input.specimen_id,"specimen_id"),uuid(input.device_id,"device_id"),input.test_user_id?uuid(input.test_user_id,"test_user_id"):null,text(input.activity_purpose,"activity_purpose"),input.protocol_identifier?text(input.protocol_identifier,"protocol_identifier"):null,input.protocol_version?text(input.protocol_version,"protocol_version"):null,input.notes?String(input.notes).trim():null,actor]);return result.rows[0];
}

export async function completeTestSession(id:unknown,actor:string,db:Db=pool){
  const result=await db.query(`UPDATE textile_lab.test_sessions SET status='completed',ended_at=now() WHERE id=$1 AND status='active' RETURNING *`,[uuid(id,"session_id")]);if(!result.rows[0])throw Object.assign(new Error("Active session not found"),{statusCode:404,code:"session_not_found"});return result.rows[0];
}

export async function appendRawReadings(sessionId:unknown,input:unknown,actor:string,db:Db=pool){
  const readings=Array.isArray(input)?input:[];if(readings.length<1||readings.length>1000)throw Object.assign(new Error("readings must contain 1 to 1000 items"),{statusCode:400,code:"invalid_readings"});
  const session=uuid(sessionId,"session_id");const inserted=[];
  for(const item of readings as Record<string,unknown>[]){
    const result=await db.query(`INSERT INTO textile_lab.raw_readings(session_id,device_id,specimen_id,channel_id,observed_at,channel_identifier,raw_value,unit,sequence_number,adapter_identifier,adapter_version,transport,source_payload,ingestion_metadata,created_by) SELECT s.id,s.device_id,s.specimen_id,c.id,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12 FROM textile_lab.test_sessions s LEFT JOIN textile_lab.channels c ON c.device_id=s.device_id AND c.channel_identifier=$3 AND c.active=true WHERE s.id=$1 AND s.status='active' ORDER BY c.version DESC NULLS LAST LIMIT 1 RETURNING *`,[session,new Date(String(item.observed_at)).toISOString(),text(item.channel_identifier,"channel_identifier"),text(item.raw_value,"raw_value",1000),item.unit?text(item.unit,"unit",50):null,item.sequence_number??null,text(item.adapter_identifier,"adapter_identifier"),text(item.adapter_version,"adapter_version"),text(item.transport,"transport"),item.source_payload?String(item.source_payload):null,item.ingestion_metadata??{},actor]);if(!result.rows[0])throw Object.assign(new Error("Active session not found"),{statusCode:404,code:"session_not_found"});inserted.push(result.rows[0]);
  }
  return inserted;
}

export async function listRawReadings(sessionId:unknown,db:Db=pool){return(await db.query(`SELECT * FROM textile_lab.raw_readings WHERE session_id=$1 ORDER BY observed_at,sequence_number NULLS LAST,id LIMIT 5000`,[uuid(sessionId,"session_id")])).rows;}

const json=(value:unknown,fallback:unknown)=>value&&typeof value==="object"?value:fallback;
const positiveInteger=(value:unknown,name:string)=>{const n=Number(value);if(!Number.isInteger(n)||n<1)throw Object.assign(new Error(`${name} is invalid`),{statusCode:400,code:"invalid_field"});return n;};
export async function createProtocol(input:Record<string,unknown>,actor:string,db:Db=pool){
 const approved=input.status==="approved";const result=await db.query(`INSERT INTO textile_lab.experiment_protocols(protocol_identifier,version,title,engineering_objective,channel_id,specimen_requirements,reference_inputs,cycle_count,baseline_seconds,hold_seconds,acceptance_criteria,status,approved_at,approved_by,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,CASE WHEN $12='approved' THEN now() END,CASE WHEN $12='approved' THEN $13::uuid END,$13) RETURNING *`,[text(input.protocol_identifier,"protocol_identifier"),text(input.version,"version"),text(input.title,"title"),text(input.engineering_objective,"engineering_objective",2000),input.channel_id?uuid(input.channel_id,"channel_id"):null,json(input.specimen_requirements,{}),Array.isArray(input.reference_inputs)?input.reference_inputs:[],input.cycle_count?positiveInteger(input.cycle_count,"cycle_count"):null,input.baseline_seconds??null,input.hold_seconds??null,json(input.acceptance_criteria,{}),approved?"approved":"draft",actor]);return result.rows[0];
}
export async function createCalibrationRun(input:Record<string,unknown>,actor:string,db:Db=pool){
 const result=await db.query(`INSERT INTO textile_lab.calibration_runs(run_identifier,protocol_id,session_id,channel_id,device_id,specimen_id,calibration_definition,status,maturity_state,notes,started_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,'in_progress','CALIBRATING',$8,now(),$9) RETURNING *`,[text(input.run_identifier,"run_identifier"),uuid(input.protocol_id,"protocol_id"),uuid(input.session_id,"session_id"),uuid(input.channel_id,"channel_id"),uuid(input.device_id,"device_id"),uuid(input.specimen_id,"specimen_id"),json(input.calibration_definition,{}),input.notes?String(input.notes):null,actor]);return result.rows[0];
}
export async function addReferenceObservation(runId:unknown,input:Record<string,unknown>,actor:string,db:Db=pool){
 const result=await db.query(`INSERT INTO textile_lab.reference_observations(calibration_run_id,raw_reading_id,reference_label,reference_value,reference_unit,cycle_number,phase,metadata,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[uuid(runId,"calibration_run_id"),uuid(input.raw_reading_id,"raw_reading_id"),text(input.reference_label,"reference_label"),input.reference_value??null,input.reference_unit?text(input.reference_unit,"reference_unit"):null,input.cycle_number?positiveInteger(input.cycle_number,"cycle_number"):null,text(input.phase,"phase"),json(input.metadata,{}),actor]);return result.rows[0];
}
export async function completeCalibrationRun(runId:unknown,input:Record<string,unknown>,db:Db=pool){const result=await db.query(`UPDATE textile_lab.calibration_runs SET status=$2,passed=$3,deviations=$4,notes=COALESCE($5,notes),ended_at=now() WHERE id=$1 AND status IN('planned','in_progress','completed') RETURNING *`,[uuid(runId,"calibration_run_id"),input.passed===true?"reviewed":input.passed===false?"failed":"completed",typeof input.passed==="boolean"?input.passed:null,Array.isArray(input.deviations)?input.deviations:[],input.notes?String(input.notes):null]);if(!result.rows[0])throw Object.assign(new Error("Calibration run not found or closed"),{statusCode:404,code:"calibration_run_not_found"});return result.rows[0];}
export async function createAlgorithmVersion(input:Record<string,unknown>,actor:string,db:Db=pool){
 if(!Array.isArray(input.result_types)||!input.result_types.length)throw Object.assign(new Error("result_types is required"),{statusCode:400,code:"invalid_field"});
 const result=await db.query(`INSERT INTO textile_lab.algorithm_versions(algorithm_identifier,version,title,result_types,implementation_metadata,checksum,status,created_by) VALUES($1,$2,$3,$4,$5,$6,'experimental',$7) RETURNING *`,[text(input.algorithm_identifier,"algorithm_identifier"),text(input.version,"version"),text(input.title,"title"),input.result_types,json(input.implementation_metadata,{}),input.checksum?text(input.checksum,"checksum"):null,actor]);return result.rows[0];
}
export type CalibrationSample={value:number;phase:string;referenceValue:number|null;cycleNumber:number|null};
export function calculateCalibrationMetrics(samples:CalibrationSample[],totalReadings:number){
 const baseline=samples.filter(s=>s.phase==="baseline").map(s=>s.value),all=samples.map(s=>s.value);if(!baseline.length)throw Object.assign(new Error("At least one numeric baseline reference is required"),{statusCode:422,code:"baseline_required"});
 const mean=(v:number[])=>v.reduce((a,b)=>a+b,0)/v.length;const baselineMean=mean(baseline);const sd=baseline.length>1?Math.sqrt(baseline.reduce((sum,v)=>sum+(v-baselineMean)**2,0)/(baseline.length-1)):0;
 const grouped=new Map<string,number[]>();for(const s of samples)if(s.referenceValue!==null){const key=String(s.referenceValue);grouped.set(key,[...(grouped.get(key)??[]),s.value]);}
 const cvs=[...grouped.values()].filter(v=>v.length>1).map(v=>{const m=mean(v);return m===0?null:Math.abs(Math.sqrt(v.reduce((sum,x)=>sum+(x-m)**2,0)/(v.length-1))/m)*100;}).filter((v):v is number=>v!==null);
 const recovery=samples.filter(s=>s.phase==="recovery").map(s=>s.value);const loads=samples.filter(s=>s.phase==="load"&&s.referenceValue!==null),unloads=samples.filter(s=>s.phase==="unload"&&s.referenceValue!==null);const pairs=loads.flatMap(l=>unloads.filter(u=>u.referenceValue===l.referenceValue).map(u=>Math.abs(l.value-u.value)));
 return {baseline_mean:baselineMean,baseline_standard_deviation:sd,baseline_relative_change:all.length?all[all.length-1]-baselineMean:null,normalised_response:baselineMean===0?null:(all[all.length-1]-baselineMean)/Math.abs(baselineMean),repeatability_cv:cvs.length?mean(cvs):null,drift:baseline.length>1?baseline[baseline.length-1]-baseline[0]:null,recovery:recovery.length?mean(recovery)-baselineMean:null,hysteresis_indicator:pairs.length?mean(pairs):null,signal_completeness:totalReadings?Math.min(100,samples.length/totalReadings*100):0};
}
export async function calculateDerivedResults(runId:unknown,algorithmId:unknown,actor:string,db:Db=pool){
 const run=await db.query(`SELECT * FROM textile_lab.calibration_runs WHERE id=$1`,[uuid(runId,"calibration_run_id")]);if(!run.rows[0])throw Object.assign(new Error("Calibration run not found"),{statusCode:404,code:"calibration_run_not_found"});
 const refs=await db.query(`SELECT rr.raw_value,ro.phase,ro.reference_value,ro.cycle_number FROM textile_lab.reference_observations ro JOIN textile_lab.raw_readings rr ON rr.id=ro.raw_reading_id WHERE ro.calibration_run_id=$1 ORDER BY rr.observed_at,rr.id`,[run.rows[0].id]);const samples=refs.rows.filter(r=>/^-?\d+(\.\d+)?$/.test(String(r.raw_value))).map(r=>({value:Number(r.raw_value),phase:r.phase,referenceValue:r.reference_value===null?null:Number(r.reference_value),cycleNumber:r.cycle_number===null?null:Number(r.cycle_number)}));const total=Number((await db.query(`SELECT count(*) FROM textile_lab.raw_readings WHERE session_id=$1 AND (channel_id=$2 OR channel_id IS NULL AND channel_identifier=(SELECT channel_identifier FROM textile_lab.channels WHERE id=$2))`,[run.rows[0].session_id,run.rows[0].channel_id])).rows[0].count);const metrics=calculateCalibrationMetrics(samples,total);const inserted=[];
 for(const [resultType,numericValue] of Object.entries(metrics)){const previous=await db.query(`SELECT id,result_version FROM textile_lab.derived_results WHERE calibration_run_id=$1 AND result_type=$2 ORDER BY result_version DESC LIMIT 1`,[run.rows[0].id,resultType]);const version=Number(previous.rows[0]?.result_version??0)+1;const result=await db.query(`INSERT INTO textile_lab.derived_results(calibration_run_id,protocol_id,channel_id,algorithm_version_id,result_type,numeric_value,unit,value_json,quality_percentage,maturity_state,result_version,supersedes_result_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'EXPERIMENTAL',$10,$11,$12) RETURNING *`,[run.rows[0].id,run.rows[0].protocol_id,run.rows[0].channel_id,uuid(algorithmId,"algorithm_version_id"),resultType,numericValue,resultType.includes("cv")||resultType.includes("completeness")?"percent":null,{sample_count:samples.length},metrics.signal_completeness,version,previous.rows[0]?.id??null,actor]);inserted.push(result.rows[0]);}
 await db.query(`UPDATE textile_lab.calibration_runs SET status='completed',maturity_state='EXPERIMENTAL',ended_at=now() WHERE id=$1`,[run.rows[0].id]);return inserted;
}
export async function reviewDerivedResult(resultId:unknown,input:Record<string,unknown>,actor:string,db:Db=pool){const result=await db.query(`INSERT INTO textile_lab.result_reviews(derived_result_id,from_state,to_state,decision,criteria_evidence,notes,reviewed_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[uuid(resultId,"derived_result_id"),text(input.from_state,"from_state"),text(input.to_state,"to_state"),text(input.decision,"decision"),json(input.criteria_evidence,{}),input.notes?String(input.notes):null,actor]);return result.rows[0];}
export async function engineeringMetrics(db:Db=pool){const result=await db.query(`SELECT (SELECT count(*) FROM textile_lab.test_sessions WHERE status='completed')::int experiments_completed,(SELECT count(*) FROM textile_lab.raw_readings)::int raw_observations,(SELECT COALESCE(EXTRACT(EPOCH FROM max(observed_at)-min(observed_at)),0) FROM textile_lab.raw_readings)::numeric capture_duration_seconds,(SELECT count(DISTINCT specimen_id) FROM textile_lab.test_sessions)::int specimens_tested,(SELECT count(DISTINCT hardware_revision) FROM textile_lab.devices WHERE hardware_revision IS NOT NULL)::int hardware_revisions_tested,(SELECT count(*) FROM textile_lab.calibration_runs WHERE status IN('completed','reviewed'))::int calibration_runs_completed,(SELECT count(*) FROM textile_lab.calibration_runs WHERE passed=true)::int calibration_runs_passed,(SELECT count(*) FROM textile_lab.derived_results)::int derived_results,(SELECT count(*) FROM textile_lab.result_reviews WHERE decision='approved' AND to_state='VALIDATED')::int validated_results`);return result.rows[0];}
