BEGIN;
ALTER TABLE finance_os.evidence_links DROP CONSTRAINT IF EXISTS evidence_links_entity_type_check;
ALTER TABLE finance_os.evidence_links ADD CONSTRAINT evidence_links_entity_type_check CHECK(entity_type IN ('assumption','product','decision','risk','company','funding','kpi','report','scenario','hire','document','expense','expense_adjustment','vat_filing','rd_work_package','rd_supplier','rd_interaction','rd_finding','rd_action','rd_rfq','rd_quotation'));
DROP TABLE IF EXISTS textile_lab.result_reviews;
DROP TABLE IF EXISTS textile_lab.derived_results;
DROP TABLE IF EXISTS textile_lab.algorithm_versions;
DROP TABLE IF EXISTS textile_lab.reference_observations;
DROP TABLE IF EXISTS textile_lab.calibration_runs;
DROP TABLE IF EXISTS textile_lab.experiment_protocols;
ALTER TABLE textile_lab.raw_readings DROP COLUMN IF EXISTS channel_id;
DROP TABLE IF EXISTS textile_lab.channels;
DROP TABLE IF EXISTS textile_lab.adapter_definitions;
DROP FUNCTION IF EXISTS textile_lab.validate_result_review();
DROP FUNCTION IF EXISTS textile_lab.validate_derived_result_lineage();
DROP FUNCTION IF EXISTS textile_lab.validate_reference_observation();
DROP FUNCTION IF EXISTS textile_lab.validate_calibration_run_links();
DROP FUNCTION IF EXISTS textile_lab.prevent_calibration_history_mutation();
ALTER TABLE textile_lab.devices DROP COLUMN IF EXISTS firmware_identifier,DROP COLUMN IF EXISTS hardware_revision;
COMMIT;
