import test from 'node:test';
import assert from 'node:assert/strict';
import {calculateCreditScenario,projectionMissing,CreditScenarioInput} from './credit-engine';
import {cashAuthority} from './finance-canonical.service';
import {decimal,minimum,format} from './finance-decimal';
import {reviewedTransferEffect} from './bank-effects';
// Synthetic test fixtures only. Never ingested into the founder review database.
const fixture:CreditScenarioInput={mode:'full',opening_purchase:'1000',opening_cash:'0',start_date:'2026-01-01',first_statement_date:'2026-01-31',due_days:5,purchase_daily_rate:'0.001',cash_daily_rate:'0.001',rate_assumption_source:'Synthetic test rate, not a contractual rate',purchase_interest_free:true,equal_rate_allocation:'purchase_first',assumptions_acknowledged:true,no_other_debt_or_arrears:true,no_further_spending:true,cash_on_hand:'2000',monthly_cash_receipts:'0',monthly_direct_cash_costs:'0'};
test('minimum payment boundary fixtures are decimal exact',()=>{for(const [balance,expected] of [['0','0.00'],['80','80.00'],['500','100.00'],['1000','100.00'],['2000','200.00']])assert.equal(format(minimum(decimal(balance))),expected);});
test('unknown values block; evidenced zero is valid',()=>{assert(projectionMissing({mode:'full'}).length>5);assert.equal(projectionMissing({...fixture,opening_purchase:'0'}).length,0);assert.equal(calculateCreditScenario({...fixture,opening_purchase:undefined}).status,'blocked');});
test('purchase paid in full avoids interest; repayment reduces cash only once',()=>{const s=calculateCreditScenario(fixture);assert('schedule' in s);assert.equal(s.estimated_interest,'0.00');assert.equal(s.estimated_total_repayment,'1000.00');assert.equal(s.schedule[0].cash_remaining,'1000.00');assert.equal(s.payoff_date,'2026-02-05');});
test('cash withdrawal accrues even when paying statement in full; residual interest survives',()=>{const s=calculateCreditScenario({...fixture,opening_purchase:'0',opening_cash:'1000'});assert('schedule' in s);assert(Number(s.estimated_interest)>0);assert(s.schedule.length>1);});
test('minimum incurs interest compared with full; fixed below minimum reports shortfall',()=>{const s=calculateCreditScenario({...fixture,mode:'minimum'});assert('schedule' in s);assert(Number(s.difference_vs_full.interest)>0);const f=calculateCreditScenario({...fixture,mode:'fixed',fixed_payment:'1',horizon_months:2});assert('schedule' in f);assert.equal(f.schedule[0].shortfall,'99.00');assert.equal(f.status,'not_repaid_within_horizon');});
test('period solver clears debt and all minimums without mutating inputs',()=>{const i={...fixture,mode:'period' as const,payoff_months:6,purchase_interest_free:false};const before=JSON.stringify(i),s=calculateCreditScenario(i);assert('schedule' in s);assert(s.payoff_date);assert(s.schedule.length<=6);assert(s.schedule.every(r=>r.shortfall==='0.00'));assert.equal(JSON.stringify(i),before);assert.deepEqual(calculateCreditScenario(i),s);assert.equal(s.financial_action,false);});
test('missing cash assumptions retain unknown runway; proposed purchase comparison isolated',()=>{const s=calculateCreditScenario({...fixture,cash_on_hand:undefined,proposed_amount:'200',proposed_kind:'purchase',proposed_date:'2026-01-15'});assert('schedule' in s);assert.equal(s.cash_runway_status,'not_available');assert.equal(s.schedule[0].cash_remaining,null);assert.equal(s.estimated_total_repayment,'1200.00');});
test('cash authority excludes credit, stale balances and unknown classifications',()=>{
 const now='2026-01-02T10:00:00.000Z';const accounts=[{id:'cash',classification:'cash_current',currency:'GBP',provider_environment:'production',status:'enabled'},{id:'credit',classification:'revolving_credit',currency:'GBP',provider_environment:'production',status:'enabled'}];
 const observations=[{id:'o1',bank_account_id:'cash',metric:'cash_booked',currency:'GBP',review_status:'reviewed',value:'50',as_of:now},{id:'o2',bank_account_id:'credit',metric:'available_credit',currency:'GBP',review_status:'reviewed',value:'999999',as_of:now}];
 assert.equal(cashAuthority(accounts,observations,now).value,'50.00');observations[1].value='999999999';assert.equal(cashAuthority(accounts,observations,now).value,'50.00');assert.equal(cashAuthority(accounts,[],now).value,null);assert.equal(cashAuthority(accounts,observations,'2026-01-05T10:00:00.000Z').value,null);observations[0].value='0';assert.equal(cashAuthority(accounts,observations,now).value,'0.00');
});
test('two repayment feed legs yield one cash debit and no revenue; drawdown is debt and cash',()=>{
 const legs=[{id:'m',classification:'cash_current' as const,amount:'-100',counterpart_id:'c',matched:true},{id:'c',classification:'revolving_credit' as const,amount:'100',counterpart_id:'m',matched:true}];assert.deepEqual(reviewedTransferEffect(legs),{cash_delta:'-100.00',debt_delta:'-100.00',revenue_delta:'0.00'});
 assert.deepEqual(reviewedTransferEffect(legs.map(l=>({...l,amount:l.id==='m'?'100':'-100'}))),{cash_delta:'100.00',debt_delta:'100.00',revenue_delta:'0.00'});
 assert.throws(()=>reviewedTransferEffect([legs[0],{...legs[1],matched:false}]));
});

test('cash forecast continues after card payoff over the same horizon',()=>{const s=calculateCreditScenario({...fixture,cash_on_hand:'2000',monthly_direct_cash_costs:'100',horizon_months:18});assert('schedule' in s);assert.equal(s.payoff_date,'2026-02-05');assert.equal(s.cash_timeline.length,18);assert(s.cash_shortfall_date);});
test('newer unreviewed cash evidence blocks an older reviewed balance',()=>{const now='2026-01-02T10:00:00.000Z';const accounts=[{id:'a',classification:'cash_current',currency:'GBP',provider_environment:'production',status:'enabled'}];const observations=[{bank_account_id:'a',metric:'cash_booked',currency:'GBP',review_status:'reviewed',value:'1',as_of:'2026-01-02T09:00:00.000Z'},{bank_account_id:'a',metric:'cash_booked',currency:'GBP',review_status:'conflicted',value:'2',as_of:now}];assert.equal(cashAuthority(accounts,observations,now).value,null);});
