import type { Section, Field } from './debt-application.template';
type Row=Record<string,any>;
export const ECONOMICS_FIELDS:Field[]=[
 {key:'retail_hypothesis',label:'Retail price hypothesis / range (not validated)',type:'text'},
 ...[['proposed_retail_price','Selected proposed retail price (£)'],['bom','Bill of materials (£)'],['engineering_cost','Specialist engineering cost (£; specify one-off basis)'],['textile_cost','Textile/material cost per unit (£)'],['electronics_cost','Electronics/sensing per unit (£)'],['assembly_cost','Assembly/manufacturing per unit (£)'],['testing_cost','Testing/validation cost (£; specify allocation basis)'],['packaging','Packaging per unit (£)'],['fulfilment','Fulfilment per unit (£)'],['channel_cost','Payment/channel costs per unit (£)'],['returns_allowance','Returns/warranty allowance per unit (£)'],['landed_unit_cost','Landed unit cost (£)']].map(([key,label]):Field=>({key,label,type:'money'})),
 {key:'vat_treatment',label:'VAT treatment / confirmation',type:'text'},
 {key:'gross_profit_per_unit',label:'Gross profit per unit (£; after VAT treatment)',type:'signed_money'},
 {key:'gross_margin',label:'Gross margin (%; show calculation basis)',type:'signed_money'},
 {key:'minimum_viable_quantity',label:'Minimum viable production quantity',type:'number'},
 {key:'supplier_moq',label:'Supplier MOQ',type:'number'},
 {key:'lead_time',label:'Lead time',type:'text'},
 {key:'production_path',label:'Production path / launch gates',type:'text'},
 {key:'calculation_basis',label:'Evidence/calculation basis; avoid summing overlapping BOM/component totals',type:'text'}
];
export const ENGINEERING_FIELDS:Field[]=[
 ...[['scope','Bounded engineering scope'],['deliverables','Deliverables'],['stages','Development stages'],['prototype_output','Prototype output'],['payment_milestones','Payment milestones'],['lead_time','Lead time'],['dependencies','Assumptions/dependencies'],['klps_supplies','What KLPS supplies'],['supplier_supplies','What Ignitec supplies'],['testing','Testing included/excluded'],['manufacturing_support','Manufacturing support included/excluded'],['ip_terms','IP ownership/licensing terms'],['post_prototype','Work required after prototype'],['budget_fit','What can fit within the proposed loan milestone'],['scope_limits','Outside actual supplier scope / questions not applicable']].map(([key,label]):Field=>({key,label,type:'text'})),
 {key:'net',label:'Quoted net price (£)',type:'money'},{key:'vat',label:'Quoted VAT (£)',type:'money'},{key:'gross',label:'Quoted gross price (£)',type:'money'}
];
export const PASS3_BUSINESS_ITEMS:Array<{code:string;section:Section;title:string;field:string;status:string;data:Row;action:string;classification:string}>=[
 {code:'product-economics',section:'economics',title:'Product economics — founder hypothesis, costs unresolved',field:'BP pricing / SA unit economics',status:'Provisional',classification:'Assumption',data:{retail_hypothesis:'Approximately £150–£250+ per garment; founder commercial hypothesis only, not a validated/launch price, sales evidence or current revenue.'},action:'Use engineering/BOM and manufacturing evidence to establish unit cost, VAT, production path and a justified price assumption.'},
 {code:'ignitec-discussion',section:'engineering',title:'Ignitec engineering discussion — scope/quote pending',field:'BP suppliers / use of funds / CFF development timing',status:'External evidence',classification:'Founder statement',data:{scope_limits:'Supplier / engineering discussion only; not contracted. Request only work within Ignitec’s actual scope; identify excluded work explicitly.'},action:'Use this checklist at the upcoming meeting; register received scope/quote through canonical evidence. No meeting date, price or contract is inferred.'},
 {code:'development-milestones',section:'requirement',title:'Defined development milestone and launch criteria',field:'BP objectives / CFF timing',status:'Founder input',classification:'Unknown',data:{finding:'KLPS remains an R&D/product-development company, not a finished commercial product. Proposed pathway: founder-funded early R&D → proposed Start Up Loan → defined engineering/product-development milestone → SEIS readiness / stronger investment case → potential angel fundraising → subsequent development/manufacturing → market entry. Later investment is not guaranteed; the loan need not fund scaled commercial manufacture.'},action:'Define the bounded milestone, prototype/validation outputs, payment dates and conditions for first product sales.'},
 {code:'fallback',section:'requirement',title:'Fallback plan — draft / founder review required',field:'BP B349:J371',status:'Review required',classification:'Assumption',data:{finding:'DRAFT — FOUNDER REVIEW REQUIRED. If KLPS commercialisation is materially delayed or does not succeed, I would seek software/technology employment or contracting. My background includes software engineering at KPMG, full-stack development, AWS Developer Associate certification and prior business experience. These skills could support a return to paid work, with actual net employment or contracting income used to help meet personal commitments and loan repayments. No job, salary or employment outcome is guaranteed. This fallback does not rely on child-related contributions or future angel investment.'},action:'Founder to review final wording and provenance of professional background; no salary or job offer is assumed.'},
 {code:'workbook-fitness',section:'requirement',title:'Usable official workbook / adviser-approved defect treatment',field:'Application document preparation',status:'External evidence',classification:'Unknown',data:{finding:'Original source identity is preserved, but the known workbook defects remain unresolved. No workbook repair, population or export is authorised in this pass.'},action:'Obtain a clean/current usable official workbook or adviser-approved treatment before population.'},
 {code:'forecast-proposed-loan',section:'forecast',title:'Proposed loan proceeds — planning only',field:'CFF loan receipt timing (official D27 treatment)',status:'Founder input',classification:'Assumption',data:{cash_direction:'Cash receipt',basis:'Separate proposed personal loan/company funding treatment and timing must be confirmed. No approval, cash receipt or facility is inferred.'},action:'Confirm proposed receipt date and company funding treatment; keep separate from revenue, credit and investment.'},
 {code:'forecast-proposed-repayment',section:'forecast',title:'Proposed loan repayment — application input only',field:'CFF 58',status:'Founder input',classification:'Assumption',data:{cash_direction:'Cash payment',basis:'Indicative terms only; lender schedule/timing not received. Excluded from existing PSB credit and never posted as canonical repayments.'},action:'Confirm forecast start and repayment timing using lender terms; avoid duplication in founder remuneration.'}
];
export function readinessGates(items:Row[],psb:Row,position:Row,app:Row,budget:Row){
 const done=(codes:string[])=>codes.every(code=>items.some(i=>i.code===code&&i.ready));
 const forecast=items.filter(i=>i.section==='forecast');
 const sales=forecast.find(i=>i.code==='forecast-sales');
 const explicitNoSales=!!sales?.ready&&Array.from({length:12},(_,i)=>sales.data?.[`m${i+1}`]).every(v=>v===0);
 const gates=[
  {id:'A',title:'Current company cash and obligations',dependencies:[],ready:position.cash.value!==null&&done(['cash','liabilities','founder-funding','recurring','vat']),action:'Confirm cut-off cash, liabilities, founder/director-loan/reimbursements, credit and tax obligations.'},
  {id:'B',title:'Evidence-led use of funds',dependencies:[],ready:budget.evidenced_eligible>=Number(app.requested_amount)&&budget.unallocated>=0&&items.filter(i=>i.section==='budget'&&i.status!=='Not applicable').every(i=>i.ready),action:'Obtain current FounderCatalyst evidence, Ignitec scope/quote and other justified development quotes. Reduce the request if supported needs are lower.'},
  {id:'C',title:'Product economics',dependencies:[],ready:done(['product-economics','commercial-2','commercial-3']),action:'Establish unit costs, VAT, production quantity/path and an explicit price hypothesis using supplier evidence.'},
  {id:'E',title:'Commercial proposition and sales gates',dependencies:['C'],ready:done(['commercial-1','commercial-4','commercial-5','commercial-6','development-milestones']),action:'Define first sellable product, target customer, UK route to market, launch criteria and justified sales timing (including an explicit no-sales case).'},
  {id:'D',title:'12-month no-investment cash-flow inputs',dependencies:explicitNoSales?['A','B']:['A','B','E'],ready:!!app.forecast_start&&forecast.length>0&&forecast.every(i=>i.ready)&&done(['forecast-loan'])&&(psb.working_reconciled||psb.ready),action:'Set opening cash and month-by-month development, operations, proposed loan receipt/repayment and justified sales timing. No speculative angel/grant receipts.'},
  {id:'F',title:'Fallback wording',dependencies:[],ready:done(['fallback']),action:'Founder review of the draft and professional-background provenance; no guaranteed salary, job, contribution or investment.'},
  {id:'G',title:'Usable official workbook',dependencies:[],ready:done(['workbook-fitness']),action:'Obtain clean/current source or adviser-approved defect treatment before population.'}
 ];
 const closed=new Set<string>();return gates.map(g=>{const waiting_on=g.dependencies.filter(id=>!closed.has(id));const ready=g.ready&&waiting_on.length===0;if(ready)closed.add(g.id);return {...g,ready,waiting_on};});
}

// Calculation preview only. Never writes to canonical cash, liabilities or schedules.
export function cashFlowPreview(items:Row[],position:Row,app:Row){
 const rows=items.filter(i=>i.section==='forecast');
 if(position.cash.value==null||!app.forecast_start||!rows.length||rows.some(i=>!i.ready||!['Cash receipt','Cash payment'].includes(i.data.cash_direction)||Array.from({length:12},(_,m)=>i.data[`m${m+1}`]).some(v=>typeof v!=='number')))return null;
 let balance=Math.round(Number(position.cash.value)*100);
 return Array.from({length:12},(_,m)=>{const opening=balance;const receipts=rows.filter(i=>i.data.cash_direction==='Cash receipt').reduce((n,i)=>n+Math.round(i.data[`m${m+1}`]*100),0);const payments=rows.filter(i=>i.data.cash_direction==='Cash payment').reduce((n,i)=>n+Math.round(i.data[`m${m+1}`]*100),0);balance+=receipts-payments;const start=new Date(app.forecast_start);return {month:new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+m,1)).toISOString().slice(0,7),opening:opening/100,receipts:receipts/100,payments:payments/100,closing:balance/100};});
}
