import { ECONOMICS_FIELDS, ENGINEERING_FIELDS } from './debt-readiness';
// Versioned intake definition, independent of workbook presentation. No source document is rewritten.
export const TEMPLATE_VERSION = 'startup-loans-pass2-v1';
export const WORKBOOK = {filename:'business-plan-template-start-up-loans-2026.xlsx',sha256:'ba0ed191912d09463047e4d6183cdb35e21e56af92ca67e086edf040e8555ef7'};
export const GUIDE = {filename:'the-start-up-loans-company-business-plan-guide-nov2020-pdf-611kb.pdf',sha256:'57cda590ad7bdae27a84f8a9ebce5cde3e3c561053203811fec789f39f193527'};
export type Section = 'requirement'|'financial'|'budget'|'commercial'|'reconciliation'|'forecast'|'document'|'economics'|'engineering';
export type Field = {key:string;label:string;type:'text'|'money'|'signed_money'|'number'|'date'|'select';options?:string[]};
const text=(key:string,label:string):Field=>({key,label,type:'text'});
const money=(key:string,label:string):Field=>({key,label,type:'money'});
const select=(key:string,label:string,options:string[]):Field=>({key,label,type:'select',options});
export const FIELDS:Record<Section,Field[]> = {
 economics:ECONOMICS_FIELDS,engineering:ENGINEERING_FIELDS,
 requirement:[text('finding','Finding / response')],
 financial:[text('finding','Evidenced position and limitations'),money('amount','Amount, only if established (£)'),text('basis','Scope / period / treatment')],
 commercial:[text('finding','Current proposition or assumption'),money('amount','Price or direct cost, if established (£)'),text('basis','Evidence, customer and timing basis'),{key:'first_sales_month',label:'First justified sales month (first day)',type:'date'},text('launch_criteria','Product launch criteria / explicit no-sales basis')],
 reconciliation:[text('historical','Historical claim (preserved)'),text('current','Current evidence'),text('prospective','Prospective wording / resolution')],
 budget:[text('description','Business requirement'),text('supplier','Supplier'),text('category','Category'),{key:'quantity',label:'Quantity',type:'number'},money('net','Total net (£)'),money('vat','Total VAT (£)'),money('gross','Total gross (£)'),{key:'payment_date',label:'Expected payment date',type:'date'},text('purpose','Business purpose'),text('milestone','Milestone enabled'),select('priority','Priority',['Unresolved','Essential','Desirable']),text('alternative','Alternative supplier / option'),select('eligibility','Loan eligibility',['Unresolved','Confirmed','Ineligible']),text('eligibility_basis','Eligibility confirmation / reference'),select('confidence','Confidence',['Unknown','Low','Medium','High'])],
 forecast:[select('cash_direction','Cash direction',['Unresolved','Cash receipt','Cash payment']),...Array.from({length:12},(_,i)=>money(`m${i+1}`,`Month ${i+1} (£)`)),text('basis','Cash timing and no-investment basis')],
 document:[text('purpose','Document purpose / readiness'),text('filename','Original filename'),text('sha256','Original SHA-256'),text('defects','Source defects / limitations')]
};
export const PSB_ROWS = [
 ...['Employment net pay','Benefits','Other income 1','Other income 2','Other income 3','Other income 4','Other income 5','Other income 6'].map((title,i)=>({row:25+i,kind:'income',title})),
 ...['Rent / mortgage','Council tax','Utilities','Phone / internet','TV licence','Insurance','Groceries','Transport','Car tax / insurance','Subscriptions','Clothing','Leisure','Savings','Existing credit repayments','Other expense 1','Other expense 2','Other expense 3','Other expense 4','Other expense 5','Other expense 6','Other expense 7'].map((title,i)=>({row:36+i,kind:'expense',title}))
];
type Seed={code:string;section:Section;title:string;field:string;action:string;status?:string;data?:Record<string,unknown>;source?:string;classification?:string};
export const SEEDS:Seed[] = [
 {code:'eligibility',section:'requirement',title:'Applicant eligibility and alternative finance',field:'Eligibility',action:'Confirm residency, right to work, age, trading start, credit assessment and why other finance is unsuitable; disclose the existing credit facility.'},
 {code:'affordability',section:'requirement',title:'Personal affordability and fallback',field:'PSB / BP B349:J371',action:'Complete private PSB using continuing net income and expenses; confirm fallback independently of future investment or partner income.'},
 {code:'cash',section:'financial',title:'Current company cash',field:'CFF D69',action:'Reconcile all company cash accounts to current statements. Available credit is not cash.',data:{finding:'Pass 1: no current cash account balance established; unknown, not zero.'}},
 {code:'liabilities',section:'financial',title:'Liabilities and existing credit',field:'CFF repayment inputs',action:'Obtain current balances, statements, minimum payments and due dates; resolve existing personal guarantee.',data:{finding:'Pass 1: £2,500 credit limit/availability and £0 debt were observed on 18 September 2026, but are stale. No current liability total established.'}},
 {code:'revenue',section:'financial',title:'Revenue and trading position',field:'BP performance / SA',action:'Reconcile current revenue and trading status from records; historical VAT Box 6 does not establish today’s revenue.',data:{finding:'25YE delivered VAT return records Box 6 £0 for its period only.'}},
 {code:'founder-funding',section:'financial',title:'Founder-paid costs and reimbursements',field:'CFF opening position',action:'Reconcile founder contributions, loans, reimbursable expenses and repayments; expense totals are not company cash.',data:{finding:'Founder-paid expenses exist; reimbursement treatment and company cash effect remain unresolved.'}},
 {code:'recurring',section:'financial',title:'Recurring business costs',field:'CFF 44:64',action:'Confirm current IONOS/ChatGPT terms and dates, business use and all continuing commitments. Exclude archived/unpurchased services.',data:{finding:'Pass 1: IONOS historical £12 annual gross; ChatGPT July £18.67 gross includes a credit and is not a normal monthly run rate.'}},
 {code:'vat',section:'financial',title:'VAT treatment and cash timing',field:'CFF tax cash timing',action:'Confirm input VAT eligibility and actual refund timing; do not assume the £33.85 reclaim was received.',data:{finding:'25YE delivered with £33.85 reclaim; receipt not evidenced.'}},
 {code:'foundercatalyst',section:'budget',title:'FounderCatalyst preparation',field:'BP B60:J71 / CFF professional fees',status:'Provisional',classification:'Assumption',source:'Founder-approved Pass 2; existing FounderCatalyst readiness engagement',action:'Obtain supplier scope/quote, VAT confirmation and Start Up Loans eligibility confirmation.',data:{description:'First external fundraising / SEIS preparation',supplier:'FounderCatalyst',category:'Professional fees',quantity:1,net:995,vat:199,gross:1194,priority:'Unresolved',eligibility:'Unresolved',confidence:'Low',purpose:'Company fundraising preparation',milestone:'Evidence-ready corporate and SEIS preparation',alternative:'Awaiting comparison'}},
 {code:'ignitec',section:'budget',title:'Ignitec scoped engineering support',field:'BP B60:J71 / CFF',status:'External evidence',action:'Obtain a bounded technical scope, quotation, timing and loan eligibility review. NDA is not a quote.',data:{description:'Scope potential prototype engineering support',supplier:'Ignitec',category:'Prototype engineering',priority:'Unresolved',eligibility:'Unresolved',confidence:'Unknown',purpose:'Resolve prototype technical requirements',milestone:'Defined and costed engineering work package'}},
 ...['First commercial proposition','Selling price','Direct cost per unit','Target customer','Route to market','Realistic sales timing'].map((title,i):Seed=>({code:`commercial-${i+1}`,section:'commercial',title,field:'BP customer / SA inputs',status:'Founder input',action:'Record a current evidence-led assumption. Historical £45–£65 pricing, 500–2,000 customers and revenue targets are not current inputs.'})),
 ...[
 ['trl','TRL claim','Historical Innovate UK application claimed TRL 4.','Current documented prototype supports TRL 3, pending controlled validation.','Explain prospective TRL 3 with scope and evidence; preserve the historical application.'],
 ['survey','Survey count','Historical application claimed 100+ surveys.','Pass 1 evidenced 44 distinct respondents (June 2026); willingness to pay is not sales.','Reconcile populations and dates; use the evidenced count and date prospectively.'],
 ['mfa','Catapult assistance','Declaration describes a maximum £15,000 assistance value.','Selection is evidenced; actual assistance value/final award agreement remains unconfirmed.','Obtain actual assistance value and dates. Do not record maximum as cash or grant received.'],
 ['names','Legal and trading names','MFA document reverses legal/trading names.','Canonical legal name is KIDS, LADIES & PARENTS, SPECIALISTS LTD; KLPS is trading identity.','Confirm legal/trading names with adviser; retain original document.'],
 ['sic','SIC discrepancy','FOS and cached Companies House SIC records differ.','FOS: 13990/62012/72190/74100; cached source: 62020.','Obtain current Companies House evidence and reconcile effective dates.'],
 ['ownership','Ownership versions','Historical and draft cap tables exist.','Verified current ownership: one Ordinary share, Emma Louise Mendez 100%; 10,000-share subdivision is proposed only.','Use verified current snapshot and date; do not treat proposed subdivision as executed.']
 ].map(([code,title,historical,current,action]):Seed=>({code:`reconcile-${code}`,section:'reconciliation',title,field:'BP / supporting evidence',status:'Review required',classification:'Conflict',action,data:{historical,current,prospective:''}})),
 ...[
 ['sales','Customer cash receipts','26'],['direct-cost','Direct cash costs','42'],['premises','Premises / utilities / insurance','44:48'],['marketing','Marketing / sales costs','49'],['operations','Other operating cash costs','50:53'],['professional','Professional / engineering fees','54'],['drawings','Personal drawings / PSB deficit','55:56'],['staff','Staff costs','57'],['existing-debt','Existing debt repayments','59:64'],['tax','VAT / tax cash flows','59:64'],['founder-cash','Evidenced founder funding','28'],['other','Other evidenced cash flows','30:36 / 59:64']
 ].map(([code,title,row]):Seed=>({code:`forecast-${code}`,section:'forecast',title,field:`CFF ${row}, months E:P`,action:'Supply 12 explicit monthly values or justify non-applicability. Zero requires confirmation. Exclude equity/grants and unverified sales; prevent double-counting budget and PSB inputs.',data:{basis:'',cash_direction:['sales','founder-cash'].includes(code)?'Cash receipt':['tax','other'].includes(code)?'Unresolved':'Cash payment'}})),
 {code:'forecast-loan',section:'requirement',title:'Proposed loan timing and repayment treatment',field:'CFF D27 / 58',action:'Confirm proposed drawdown/start month and model terms separately. Request and indicative payment are not an approved facility or schedule.'},
 {code:'original-workbook',section:'document',title:'Original official workbook (unchanged)',field:'Source template',status:'Review required',action:'Register the exact original in private canonical evidence and compare SHA-256. Await clean/replacement official template before population.',data:{purpose:'Immutable source, not application data',...WORKBOOK,defects:'Hidden Loan Calculator named ranges contain #REF!; CFF D73 stress formula contains #REF!; SA J24 example uses markup not gross margin; SA print area omits notes; unsupported Excel extensions make round-trip editing unsafe.'}},
 {code:'original-guide',section:'document',title:'Original Start Up Loans guide',field:'Source guidance',status:'Review required',action:'Register original guide in private evidence; reconcile 2020 guidance with current official requirements.',data:{purpose:'Reference guidance, November 2020',...GUIDE,defects:'Guide and 2026 workbook have structural differences; use workbook field map without altering either original.'}},
 ...['Business plan','Personal survival budget','12-month cash-flow forecast','Use-of-funds quotes','Supporting evidence pack'].map((title,i):Seed=>({code:`document-${i+1}`,section:'document',title,field:'Future application document version',action:'Resolve inputs first. No final application is populated, generated or submitted in Pass 2.',data:{purpose:'Not drafted'}}))
];
