// Private server-side intake template. This is provider correspondence, not executed instructions.
export const REQUEST_SOURCE = 'Carolina Rimoldi, FounderCatalyst email supplied by founder on 2026-09-15; original email date unknown';
export const FOUNDER_DECISION = 'Founder decision 2026-09-15: KLPS is bootstrapped with no previous external equity round. Proceed with FounderCatalyst to prepare for the first external raise and SEIS readiness. Founder confirms £995 + VAT specifically agreed for KLPS. Provider document still to be linked. No payable, payment, final round size, valuation or equity terms authorised. £250,000 is planning only; £260,000 is a provider-suggested alternative only.';

// code, requirement, location, document, owner, dependency, classification, next action
export const READINESS_REQUIREMENTS = [
  ['FC01','Confirm KLPS-specific service scope and agreed £995 + VAT price','Company / engagement','Provider quote or agreement','Founder / FounderCatalyst','','AVAILABLE + REVIEW REQUIRED','Link provider documentation to the founder-confirmed agreement; do not create a payable.'],
  ['FC02','Create account and add company','Canonical company','Platform setup evidence','Founder','','EXTERNAL ACTION REQUIRED','Check existing account before creating one; use canonical company identity.'],
  ['FC03','Enter founder and any co-founder details','Canonical company','Confirmed founder details','Founder','FC02','FOUNDER INPUT REQUIRED','Confirm current details and whether any co-founders exist.'],
  ['FC04','Current cap table for provider review','Ownership reconciliation','Current register and corporate event evidence','Founder / corporate adviser','CR01','CONFLICT — REVIEW REQUIRED','Supply reconciled actual holdings; identify pending changes separately and clarify platform treatment.'],
  ['FC05','Proposed share subdivision — separate review decision','Corporate decisions','Separate decision and supporting corporate advice','Founder / corporate adviser','CR01','FOUNDER INPUT REQUIRED','Record a separate decision. No share split or SH02 filing is authorised.'],
  ['FC06','Start Full initial funding round','Engagement / external platform','Platform setup evidence','Founder','FC02','EXTERNAL ACTION REQUIRED','Clarify a preparation-only setup with provider; do not invent transaction terms.'],
  ['FC07','Complete all Funding Round Step 1 details','Engagement / scenario','Reviewed round inputs','Founder','FC06','FOUNDER INPUT REQUIRED','Record unknown inputs and seek provider guidance; leave valuation and final round size unset.'],
  ['FC08','Review Warranty Limitations and suggested defaults','Legal decisions','Reviewed terms','Founder / corporate adviser','FC07','FOUNDER INPUT REQUIRED','Do not accept legal defaults automatically.'],
  ['FC09','Defer Specific Disclosures for now as instructed','Legal decisions','Disclosure review record','Founder / corporate adviser','FC07','EXTERNAL ACTION REQUIRED','Record deferral and revisit before executing any documents.'],
  ['FC10','Consider £260,000 for combined SEIS/EIS assurance','Fundraising scenarios','Optional scenario and decision','Founder','','FOUNDER INPUT REQUIRED','Provider suggestion only; no change to strategy or approved transaction.'],
  ['FC11','Reach Step 2 Invited and pause','Engagement milestones','Platform milestone evidence','Founder','FC07','EXTERNAL ACTION REQUIRED','Pause at Step 2; do not invite investors automatically.'],
  ['FC12','Pay on platform before provider finalises pack','Financial OS','Invoice and reconciled payment evidence','Founder','FC01','FOUNDER INPUT REQUIRED','Obtain invoice and separate payment authorisation; no liability is created from budget.'],
  ['FC13','Enter mobile number in account settings','Secure founder details','Platform confirmation','Founder','FC02','FOUNDER INPUT REQUIRED','Confirm privately; do not put the number in general notes.'],
  ['FC14','Enter corporation tax UTR; request replacement only if missing','Secure corporate tax evidence','UTR letter / secure reference','Founder','FC02','MISSING','Locate canonical tax evidence; do not expose the UTR in checklist notes.'],
  ['FC15','Make shareholders agreement accessible to provider','Legal evidence','Current or provider-generated agreement','Founder / FounderCatalyst','FC07','MISSING','Track generated document as draft, with legal review before signature.'],
  ['FC16','Make articles of association accessible to provider','Corporate evidence','Current operative articles','Founder / FounderCatalyst','CR01','AVAILABLE + REVIEW REQUIRED','Verify current articles against incorporation and subsequent changes.'],
  ['FC17','Make populated HMRC covering letter accessible','Fundraising evidence','Submission covering letter','FounderCatalyst','FC07','EXTERNAL ACTION REQUIRED','Track generated version and founder review.'],
  ['FC18','Provide latest pitch deck as PDF below 10 MB','Investor Data Room / pitch deck','Approved PDF','Founder','','AVAILABLE + REVIEW REQUIRED','Select current canonical version; verify size, content and evidence.'],
  ['FC19','Provide latest forecast as Excel below 10 MB','Financial OS / model snapshot','Excel forecast','Founder','','MISSING','Locate or generate derivative of the canonical forecast.'],
  ['FC20','Forecast must cover at least three future years','Financial OS / forecast','Dated forecast','Founder','FC19','MISSING','Validate coverage from the proposed submission date.'],
  ['FC21','Show proposed investment entering forecast cash','Financial OS / scenario','Forecast scenario','Founder','FC19','MISSING','Show inflow only in scenario, never actual received investment.'],
  ['FC22','Show spending matching pitch-deck use of funds','Financial OS / assumptions','Forecast and deck reconciliation','Founder','FC18, FC19','MISSING','Reconcile amounts, categories and timing.'],
  ['FC23','Explain funding need with investment removed','Financial OS / sensitivity','Without-investment sensitivity','Founder','FC19','MISSING','Report actual cash need; never manufacture a gap to match a target raise.'],
  ['FC24','Provider reviews deck and forecast and suggests revisions','Engagement correspondence','Review and revised versions','FounderCatalyst','FC18, FC19, FC20, FC21, FC22, FC23','EXTERNAL ACTION REQUIRED','Track feedback and approval of each revised version.'],
  ['FC25','Create support ticket with Reason = (S)EIS advance assurance submission and requested body','Engagement / submission record','Approved pack and ticket receipt','Founder','FC11, FC12, FC13, FC14, FC15, FC16, FC17, FC24','EXTERNAL ACTION REQUIRED','Requires separate external submission authorisation.'],
  ['FC26','Track further communication through support ticket','Engagement correspondence','Ticket and correspondence','Founder / FounderCatalyst','FC25','EXTERNAL ACTION REQUIRED','Record ticket ID, supplied versions, dates and external decisions.'],
  ['CR01','Reconcile current ownership against incorporation and later events','Canonical company / ownership','Register of members, filings, share and instrument records','Founder / corporate adviser','','AVAILABLE + REVIEW REQUIRED','Incorporation evidence supports one ordinary £1 share; current ownership requires subsequent-event review.'],
  ['CR02','Resolve company identity, SIC and date discrepancies','Canonical company','Current corporate evidence','Founder / corporate adviser','','CONFLICT — REVIEW REQUIRED','Review historical SIC differences and exported date conversion without rewriting history.'],
  ['CR03','Verify SEIS/EIS milestones against actual evidence','Canonical company / tax evidence','Submission, correspondence and decision evidence','Founder / FounderCatalyst','','MISSING','Approval and eligibility remain pending evidence.'],
] as const;
