import test from 'node:test';
import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {randomUUID} from 'crypto';
import {narrativeSequence,assetFits} from '../growth/planner-template';
import {sourceMediaType} from '../growth/planning-media.service';
import {createNarrativePlan,listNarrativePlans,updateNarrativePlan,assertPlannedContent,planningTimeline,profilePlanningMedia} from '../growth/planner.service';
import {getMissionCandidates,acceptMissionCandidate,evaluateMissionCompletion} from '../growth/mission-candidate.service';
const sequence=()=>narrativeSequence(['linkedin','instagram','tiktok'],'2026-11-01','2026-11-22','Recorded supplier discovery');
test('Instagram has six designed slots and three protected genuine-media reservations in a story sequence',()=>{
 const rows=sequence(),ig=rows.filter(x=>x.platform==='instagram');assert.equal(ig.length,9);assert.equal(ig.filter(x=>x.requirement.kind==='genuine').length,3);assert.equal(ig.filter(x=>x.requirement.kind==='designed').length,6);assert.equal(new Set(ig.map(x=>x.title)).size,9);assert(rows.every((x,i)=>x.order===i+1));assert(rows.every((x,i)=>i===0||x.scheduled_at>=rows[i-1].scheduled_at));assert(ig.some(x=>x.role==='conversion'));assert(ig.some(x=>x.cta==='No mandatory waitlist CTA.'));
 const li=rows.find(x=>x.platform==='linkedin')!,tt=rows.find(x=>x.platform==='tiktok')!;assert.notEqual(li.approach,tt.approach);assert.equal(tt.execution,'manual');assert.equal(tt.requirement.media_type,'video');assert(!rows.some(x=>x.platform==='facebook'));assert.throws(()=>narrativeSequence(['bad'],'2026-11-01','2026-11-22','x'));
});
test('genuine-media reuse requires recorded origin, approval, stored file and platform/format suitability',()=>{
 const b=sequence().find(x=>x.platform==='tiktok')!,a={approved_for_use:true,storage_key:'private-key',provenance_kind:'genuine_founder',mime_type:'video/mp4',aspect_ratio:'9:16',duration_seconds:30,suitable_platforms:['tiktok']};assert(assetFits(b,a));assert(assetFits(b,{...a,storage_key:null,stored_version:true}));for(const patch of [{provenance_kind:'generated'},{provenance_kind:'unknown'},{approved_for_use:false},{storage_key:null},{mime_type:'image/jpeg'},{aspect_ratio:'16:9'},{suitable_platforms:['instagram']},{duration_seconds:0}])assert.equal(assetFits(b,{...a,...patch}),false);
});
test('private source intake rejects HTML and unsupported media bytes',()=>{assert.throws(()=>sourceMediaType(Buffer.from('<html>not an image</html>')));const b=Buffer.alloc(32);b.write('ftyp',4);b.write('mp42',8);assert.equal(sourceMediaType(b).mime,'video/mp4');});
const url=process.env.GROWTH_PLANNER_TEST_DATABASE_URL;
test('real schema: founder narrative sequencing, lineage, asset reuse, missions, calendar and approval boundaries',{skip:!url},async t=>{
 const u=new URL(url!);assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55481');assert.equal(u.pathname,'/growth_planner_test');
 const db=new Pool({connectionString:url});const fetch=global.fetch;global.fetch=async()=>{throw Error('Provider calls forbidden');};
 try{
 const n=(await db.query("SELECT n.*,w.owner_user_id FROM growth_os.narrative_opportunities n JOIN growth_os.workspaces w ON w.id=n.workspace_id WHERE n.status='accepted' AND n.source_kind='rd_discovery' ORDER BY n.created_at LIMIT 1")).rows[0];assert(n,'Founder-accepted genuine discovery is in the production snapshot');const w=n.workspace_id,user=n.owner_user_id;
 const before=(await db.query('SELECT (SELECT count(*) FROM growth_os.social_publish_jobs)::int jobs,(SELECT count(*) FROM growth_os.social_content_variants)::int variants,(SELECT count(*) FROM public.waitlist_signups)::int signups')).rows[0];
 const input={opportunity_id:n.id,platforms:['linkedin','instagram','tiktok'],start_date:'2026-11-01',end_date:'2026-11-22'};
 let id:string;await t.test('concurrent creation is idempotent and preserves canonical source lineage',async()=>{const [a,b]=await Promise.all([createNarrativePlan(w,user,input,db),createNarrativePlan(w,user,input,db)]);assert.equal(a.id,b.id);id=a.id;const p=(await listNarrativePlans(w,db)).plans.find(p=>p.id===id)!;assert.equal(p.narrative_plan.source_insight_id,n.insight_id);assert.equal(p.items.length,15);assert(p.items.every((i:any)=>i.status==='idea'&&!i.caption&&!i.script&&!i.published_at&&i.platform_brief.source_opportunity_id===n.id));await assert.rejects(createNarrativePlan(w,randomUUID(),input,db),/founder/);});
 const get=async()=>(await listNarrativePlans(w,db)).plans.find(p=>p.id===id)!;const edits=(p:any)=>p.items.sort((a:any,b:any)=>a.platform_brief.order-b.platform_brief.order).map((i:any)=>({...i.platform_brief,id:i.id,scheduled_at:i.scheduled_at}));
 await t.test('planning approval requires individual decisions and creates no social approval',async()=>{let p=await get();await assert.rejects(updateNarrativePlan(w,user,id,{version:p.planning_version,items:edits(p),approve:true},db),/Accept or exclude/);await assert.rejects(assertPlannedContent(w,p.items[0].id,db),/Review/);const items=edits(p).map((i:any)=>({...i,review:'accepted'}));await updateNarrativePlan(w,user,id,{version:p.planning_version,items,approve:true},db);p=await get();assert(p.planning_approved_at);const text=p.items.find((i:any)=>i.platform==='linkedin');await assertPlannedContent(w,text.id,db);assert.equal(text.status,'idea');await assert.rejects(updateNarrativePlan(w,user,id,{version:1,items},db),/changed/);});
 await t.test('genuine-media reservation cannot be replaced; approved existing media can be bound once and reused',async()=>{let p=await get();const video=p.items.find((i:any)=>i.platform==='tiktok');const asset=(await db.query("INSERT INTO growth_os.media_assets(workspace_id,filename,display_name,asset_type,mime_type,storage_key,approved_for_use,provenance_kind,aspect_ratio,duration_seconds,suitable_platforms) VALUES($1,'local.mp4','Local fixture','video','video/mp4','local-private',true,'generated','9:16',30,'[\"tiktok\",\"instagram\"]') RETURNING id",[w])).rows[0];let items=edits(p).map((i:any)=>i.id===video.id?{...i,asset_id:asset.id,requirement:{kind:'designed'}}:i);await assert.rejects(updateNarrativePlan(w,user,id,{version:p.planning_version,items},db),/Asset must/);await profilePlanningMedia(w,user,asset.id,{provenance_confirmed:true,provenance_kind:'genuine_founder',provenance_notes:'Local genuine footage fixture',aspect_ratio:'9:16',duration_seconds:30,suitable_platforms:['instagram','tiktok']},db);p=await get();assert(p.items.find((i:any)=>i.id===video.id).suggested_assets.some((a:any)=>a.id===asset.id));items=edits(p).map((i:any)=>i.requirement.kind==='genuine'?{...i,asset_id:asset.id}:i);await updateNarrativePlan(w,user,id,{version:p.planning_version,items,approve:true},db);p=await get();assert(p.items.filter((i:any)=>i.platform_brief.requirement.kind==='genuine').every((i:any)=>i.asset_ready));assert.equal(p.items.find((i:any)=>i.id===video.id).platform_brief.requirement.kind,'genuine');assert(!JSON.stringify(p).includes('local-private'));await assertPlannedContent(w,video.id,db);await db.query('UPDATE growth_os.media_assets SET approved_for_use=false WHERE id=$1',[asset.id]);await assert.rejects(assertPlannedContent(w,video.id,db),/Review/);});
 await t.test('Mission Control uses existing deduplication and verified outcomes',async()=>{const candidates=await getMissionCandidates(w,new Date('2026-10-02'),db);const c=candidates.find(c=>c.candidate_type==='provide_media');assert(c);const m=await acceptMissionCandidate(w,c!.deduplication_key,'2026-10-02',new Date('2026-10-02'),db);assert(m);await assert.rejects(acceptMissionCandidate(w,c!.deduplication_key,'2026-10-02',new Date('2026-10-02'),db));const e=await evaluateMissionCompletion(w,m,new Date(),db);assert.equal(e.satisfied,false);});
 await t.test('intended dates stay in Studio; duplicate calendar publishing rows are blocked',async()=>{const p=await get(),item=p.items[0];await assert.rejects(db.query("INSERT INTO growth_os.calendar_entries(workspace_id,content_item_id,title,entry_type,starts_at) VALUES($1,$2,'Duplicate','publishing',now())",[w,item.id]),/owns its planned date/);const timeline=await planningTimeline(w,db);assert(timeline.plans.some(p=>p.id===id));assert.equal(timeline.execution.length,0);});
 await t.test('confidential source blocks further planning and provider preparation',async()=>{await db.query("UPDATE growth_os.narrative_opportunities SET status='confidential' WHERE id=$1",[n.id]);const p=await get();assert.equal(p.current,false);await assert.rejects(updateNarrativePlan(w,user,id,{version:p.planning_version,items:edits(p)},db),/source must/);await assert.rejects(assertPlannedContent(w,p.items[0].id,db),/Review/);});
 const after=(await db.query('SELECT (SELECT count(*) FROM growth_os.social_publish_jobs)::int jobs,(SELECT count(*) FROM growth_os.social_content_variants)::int variants,(SELECT count(*) FROM public.waitlist_signups)::int signups')).rows[0];assert.deepEqual(after,before);
 }finally{global.fetch=fetch;await db.end();}
});
