import test from 'node:test';
import assert from 'node:assert/strict';
import {Pool} from 'pg';
import {randomUUID} from 'crypto';
import sharp from 'sharp';
import {narrativeSequence} from '../growth/planner-template';
import {prepareCopy,designedGenerator,visualGenerator,GenerationRequest,briefFingerprint} from '../growth/production-generation';
import {changeProduction,listProduction} from '../growth/production.service';
import {assertProduction} from '../growth/production-state';
import {addNarrativePlatforms,updateNarrativePlan,listNarrativePlans,profilePlanningMedia} from '../growth/planner.service';
const evidence={kind:'rd_discovery',state:'Discovery Completed'};
const request=(platform='instagram',position=1):GenerationRequest=>({content_id:'test',brief:narrativeSequence([platform],'2026-11-01','2026-11-20','Supplier discovery').find(x=>x.position===position)!,theme:'founder_build_journey',evidence,constraints:'No validation',neighbours:[],approved_assets:[],version:1});
test('platform-native copy uses only explicit evidence states, not arbitrary briefing claims',()=>{
 const drafts=['linkedin','facebook','instagram','x','tiktok','snapchat'].map(p=>prepareCopy(request(p)));assert.equal(new Set(drafts.map(x=>x.caption)).size,6);assert(drafts[0].caption.includes('For me'));assert(drafts[1].caption.includes('behind-the-scenes'));assert(drafts[4].script.includes('0–3s'));assert(drafts[4].guidance.includes('9:16'));assert(drafts[5].caption.includes('Open the link'));assert(drafts[3].caption.length<280);
 const r=request();r.brief.approach='We have a clinical partnership and secured funding';assert(!prepareCopy(r).caption.includes('secured funding'));assert.throws(()=>prepareCopy({...r,evidence:{kind:'fabricated'}}));
 assert(!prepareCopy(r).caption.includes('waitlist'));const conversion=request('instagram',8);conversion.tracked_link={id:'canonical',generated_url:'https://klps.co.uk/waitlist?klps_ref=abc'};assert(prepareCopy(conversion).guidance.includes('klps_ref=abc'));assert(prepareCopy(conversion).caption.includes('profile'));
});
test('renderer produces a real branded 1080×1350 JPEG and refuses genuine slots or paid generation',async()=>{
 const r=request(),image=await designedGenerator.generate(r,prepareCopy(r)),m=await sharp(image.bytes).metadata();assert.equal(m.width,1080);assert.equal(m.height,1350);assert.equal(m.format,'jpeg');assert.equal(image.origin,'designed');assert.throws(()=>visualGenerator('external-ai'),/not enabled/);const genuine=request('instagram',3);await assert.rejects(designedGenerator.generate(genuine,prepareCopy(genuine)),/Genuine/);
});
const url=process.env.GROWTH_PRODUCTION_TEST_DATABASE_URL;
test('real schema production lifecycle, independent approvals, disclosure, idempotency and zero publishing',{skip:!url},async t=>{
 const u=new URL(url!);assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55481');assert.equal(u.pathname,'/growth_production_test');const db=new Pool({connectionString:url});
 const r2=require('../services/r2.service');const saved={upload:r2.uploadToR2,del:r2.deleteFromR2};let uploads=0;r2.uploadToR2=async()=>{uploads++;};r2.deleteFromR2=async()=>{};const fetch=global.fetch;global.fetch=async()=>{throw Error('External provider calls forbidden');};
 try{
 const n=(await db.query("SELECT n.*,w.owner_user_id FROM growth_os.narrative_opportunities n JOIN growth_os.workspaces w ON w.id=n.workspace_id WHERE n.status='accepted' AND n.source_kind='rd_discovery' LIMIT 1")).rows[0];assert(n);const w=n.workspace_id,user=n.owner_user_id;
 const before=(await db.query('SELECT (SELECT count(*) FROM growth_os.social_publish_jobs)::int jobs,(SELECT count(*) FROM growth_os.social_content_variants)::int variants,(SELECT count(*) FROM public.waitlist_signups)::int signups')).rows[0];
 let plan=(await listNarrativePlans(w,db)).plans.find(p=>p.narrative_opportunity_id===n.id)!;assert(plan);const items=plan.items.sort((a:any,b:any)=>a.platform_brief.order-b.platform_brief.order).map((i:any)=>({...i.platform_brief,id:i.id,scheduled_at:i.scheduled_at,review:'accepted'}));await updateNarrativePlan(w,user,plan.id,{version:plan.planning_version,items,approve:true},db);
 const ig=plan.items.find((i:any)=>i.platform==='instagram'&&i.platform_brief.requirement.kind==='designed'),genuine=plan.items.find((i:any)=>i.platform==='instagram'&&i.platform_brief.requirement.kind==='genuine');assert(ig&&genuine);
 const row=async(id=ig.id)=>(await db.query('SELECT * FROM growth_os.content_items WHERE id=$1',[id])).rows[0];
 const run=async(action:string,extra:Record<string,any>={},target=ig.id)=>changeProduction(w,user,target,{action,version:(await row(target)).production_state?.version??0,...extra},db);
 await t.test('founder boundary, idempotent version checks and copy proposals never approve',async()=>{await assert.rejects(changeProduction(w,randomUUID(),ig.id,{action:'copy',version:0},db),/founder/);await run('copy');let a=await row();assert(!a.production_state.candidates[0].approved_at);await assert.rejects(assertProduction(w,ig.id,db),/copy/);await assert.rejects(changeProduction(w,user,ig.id,{action:'copy',version:0},db),/changed/);await run('approve',{candidate_id:a.production_state.copy_id,confirmed:true});a=await row();assert(a.production_state.candidates[0].approved_at);await assert.rejects(assertProduction(w,ig.id,db),/asset/);});
 await t.test('rendered media is private and unapproved; approvals are independent',async()=>{await run('visual');let a=await row(),candidate=a.production_state.candidates.find((x:any)=>x.id===a.production_state.asset_id);const m=(await db.query('SELECT * FROM growth_os.media_assets WHERE id=$1',[candidate.media_asset_id])).rows[0];assert.equal(m.approved_for_use,false);assert.equal(m.provenance_kind,'designed');assert.equal(m.mime_type,'image/jpeg');assert.equal(m.production_provenance.content_id,ig.id);assert.equal(uploads,1);assert(a.production_state.candidates.find((x:any)=>x.id===a.production_state.copy_id).approved_at);await run('approve',{candidate_id:candidate.id,confirmed:true});await assertProduction(w,ig.id,db);a=await row();await assert.rejects(assertProduction(w,ig.id,db,{copy:'Other text',media_references:[]}),/differs/);const data=await listProduction(w,db);assert(!JSON.stringify(data).includes('growth-source/'));});
 await t.test('editing copy creates a new unapproved candidate but preserves asset approval',async()=>{let a=await row();await run('edit',{candidate_id:a.production_state.copy_id,caption:'Founder-edited draft for review',script:''});a=await row();assert(a.production_state.candidates.find((x:any)=>x.id===a.production_state.asset_id).approved_at);await assert.rejects(assertProduction(w,ig.id,db),/copy/);await run('approve',{candidate_id:a.production_state.copy_id,confirmed:true});await assertProduction(w,ig.id,db);await db.query("UPDATE growth_os.content_items SET caption='Changed outside production' WHERE id=$1",[ig.id]);a=await row();assert(!a.production_state.candidates.find((x:any)=>x.id===a.production_state.copy_id).approved_at);await assert.rejects(assertProduction(w,ig.id,db),/copy/);});
 await t.test('genuine reservations reject generation and designed replacements; failures preserve draft state',async()=>{await assert.rejects(run('visual',{},genuine.id),/Genuine/);assert.equal((await row(genuine.id)).production_state,null);const a=await row();const m=a.production_state.candidates.find((x:any)=>x.kind==='asset');await assert.rejects(run('attach',{media_asset_id:m.media_asset_id},genuine.id),/provenance/);await run('copy',{},genuine.id);assert((await row(genuine.id)).production_state.candidates[0].guidance.includes('Film genuine'));});
 await t.test('asset metadata edits revoke asset use; rejected and stale candidates cannot approve',async()=>{let a=await row(),asset=a.production_state.candidates.find((x:any)=>x.id===a.production_state.asset_id);await db.query("UPDATE growth_os.media_assets SET provenance_notes='Changed provenance' WHERE id=$1",[asset.media_asset_id]);assert.equal((await db.query('SELECT approved_for_use FROM growth_os.media_assets WHERE id=$1',[asset.media_asset_id])).rows[0].approved_for_use,false);await run('reject',{candidate_id:asset.id});await assert.rejects(run('approve',{candidate_id:asset.id,confirmed:true}),/rejected/);await db.query("UPDATE growth_os.content_items SET platform_brief=jsonb_set(platform_brief,'{approach}','\"Changed brief\"') WHERE id=$1",[ig.id]);a=await row();await assert.rejects(run('select',{candidate_id:a.production_state.copy_id}),/brief changed/);});
 await t.test('additional platform briefs reuse the campaign and require new planning approval',async()=>{let p=(await listNarrativePlans(w,db)).plans.find(p=>p.id===plan.id)!;await addNarrativePlatforms(w,user,p.id,{version:p.planning_version,platforms:['facebook','x','tiktok']},db);p=(await listNarrativePlans(w,db)).plans.find(p=>p.id===plan.id)!;assert(!p.planning_approved_at);assert.equal(p.items.filter((i:any)=>i.platform==='tiktok').length,3);await assert.rejects(run('copy'),/Approve the narrative/);await assert.rejects(addNarrativePlatforms(w,user,p.id,{version:p.planning_version,platforms:['facebook']},db),/not already/);await updateNarrativePlan(w,user,p.id,{version:p.planning_version,items:p.items.sort((a:any,b:any)=>a.platform_brief.order-b.platform_brief.order).map((i:any)=>({...i.platform_brief,id:i.id,scheduled_at:i.scheduled_at,review:'accepted',asset_id:null})),approve:true},db);});
 await t.test('conversion links reuse Phase 5A lineage and are not duplicated',async()=>{const p=(await listNarrativePlans(w,db)).plans.find(p=>p.id===plan.id)!;const conversion=p.items.find((i:any)=>i.platform==='instagram'&&i.platform_brief.role==='conversion');const first=await run('bind_link',{},conversion.id),second=await run('bind_link',{},conversion.id);assert.equal(first.tracked_link.id,second.tracked_link.id);await run('copy',{},conversion.id);assert((await row(conversion.id)).production_state.candidates[0].guidance.includes(first.tracked_link.generated_url));});
 await t.test('confidential source blocks generation; no jobs, variants or signup changes',async()=>{await db.query("UPDATE growth_os.narrative_opportunities SET status='confidential' WHERE id=$1",[n.id]);await assert.rejects(run('copy'),/source must/);const after=(await db.query('SELECT (SELECT count(*) FROM growth_os.social_publish_jobs)::int jobs,(SELECT count(*) FROM growth_os.social_content_variants)::int variants,(SELECT count(*) FROM public.waitlist_signups)::int signups')).rows[0];assert.deepEqual(after,before);});
 }finally{r2.uploadToR2=saved.upload;r2.deleteFromR2=saved.del;global.fetch=fetch;await db.end();}
});

test('optional external adapter contract is sanitised, unretried, and unreachable through the production registry',async()=>{
 const {openAIImageAdapter}=await import('../growth/production-openai.adapter');let calls=0;const r=request(),bytes=(await designedGenerator.generate(r,prepareCopy(r))).bytes;
 const adapter=openAIImageAdapter('test-secret',async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/images/generations');const body=JSON.parse(String(options?.body));assert.equal(body.model,'gpt-image-1.5');assert.equal(body.n,1);assert.equal(body.output_format,'jpeg');assert(!body.prompt.includes(r.content_id));assert(!body.prompt.includes('Supplier'));return new Response(JSON.stringify({data:[{b64_json:bytes.toString('base64')}]}),{status:200});});
 assert.throws(()=>visualGenerator(adapter.id),/not enabled/);const result=await adapter.generate(r,prepareCopy(r));assert.equal(result.origin,'generated');assert.equal(result.provenance?.model,'gpt-image-1.5');assert.equal(calls,1);
 const bad=openAIImageAdapter('test-secret',async()=>new Response('private upstream detail test-secret',{status:429}));await assert.rejects(bad.generate(r,prepareCopy(r)),e=>e instanceof Error&&e.message.includes('429')&&!e.message.includes('test-secret'));
 await assert.rejects(adapter.generate(request('instagram',3),prepareCopy(request('instagram',3))),/Genuine/);assert.equal(calls,1);
});
