/// <reference types="node" />
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
const read=(p:string)=>readFileSync(path.resolve(p),"utf8");
test("Textile Lab migration is isolated, relational and append-only",()=>{const sql=read("server/sql/20260813_textile_intelligence_lab_phase1.sql");for(const table of ["devices","specimens","test_assignments","test_sessions","raw_readings"])assert.match(sql,new RegExp(`CREATE TABLE textile_lab\\.${table}`));assert.match(sql,/prevent_raw_reading_mutation/);assert.match(sql,/BEFORE UPDATE ON textile_lab\.raw_readings/);assert.match(sql,/BEFORE DELETE ON textile_lab\.raw_readings/);assert.doesNotMatch(sql,/INSERT INTO lema\.(signals|daily_sessions)/);});
test("Textile Lab API is founder-admin protected and separately mounted",()=>{const routes=read("server/src/textile-lab/textile-lab.routes.ts"),index=read("server/src/index.ts");assert.match(routes,/router\.use\(requireDataRoomAuth,requireAdmin\)/);assert.match(index,/app\.use\("\/api\/textile-lab", textileLabRoutes\)/);});
test("raw capture stores provenance and never uses legacy body stores",()=>{const service=read("server/src/textile-lab/textile-lab.service.ts");for(const field of ["observed_at","channel_identifier","raw_value","adapter_identifier","adapter_version","transport","source_payload","ingestion_metadata"])assert.match(service,new RegExp(field));for(const forbidden of ["lema.signals","daily_sessions","waist_measurements"])assert.doesNotMatch(service,new RegExp(forbidden));});
test("account population and activity purpose remain separate and traction is opt-in",()=>{const migration=read("server/sql/20260813_textile_intelligence_lab_phase1.sql"),founder=read("server/src/routes/founder.ts"),summary=read("server/src/routes/summary.routes.ts");for(const population of ["founder_experiment","controlled_test","real_world_test","genuine_beta"])assert.match(migration,new RegExp(population));for(const purpose of ["engineering","calibration","controlled_test","real_world_wear","genuine_product_use"])assert.match(migration,new RegExp(purpose));assert.match(migration,/analytics_population_snapshot/);assert.match(migration,/analytics_eligible boolean NOT NULL DEFAULT false/);assert.doesNotMatch(migration,/@gmail|@live/i);assert.ok((founder.match(/analytics_eligible=true/g)??[]).length>=5);assert.ok((summary.match(/analytics_eligible=true/g)??[]).length>=2);});
