/// <reference types="node" />
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { calculateCalibrationMetrics } from "../textile-lab/textile-lab.service";
const read=(p:string)=>readFileSync(path.resolve(p),"utf8");
test("Textile Lab migration is isolated, relational and append-only",()=>{const sql=read("server/sql/20260813_textile_intelligence_lab_phase1.sql");for(const table of ["devices","specimens","test_assignments","test_sessions","raw_readings"])assert.match(sql,new RegExp(`CREATE TABLE textile_lab\\.${table}`));assert.match(sql,/prevent_raw_reading_mutation/);assert.match(sql,/BEFORE UPDATE ON textile_lab\.raw_readings/);assert.match(sql,/BEFORE DELETE ON textile_lab\.raw_readings/);assert.doesNotMatch(sql,/INSERT INTO lema\.(signals|daily_sessions)/);});
test("Textile Lab API is founder-admin protected and separately mounted",()=>{const routes=read("server/src/textile-lab/textile-lab.routes.ts"),index=read("server/src/index.ts");assert.match(routes,/router\.use\(requireDataRoomAuth,requireAdmin\)/);assert.match(index,/app\.use\("\/api\/textile-lab", textileLabRoutes\)/);});
test("raw capture stores provenance and never uses legacy body stores",()=>{const service=read("server/src/textile-lab/textile-lab.service.ts");for(const field of ["observed_at","channel_identifier","raw_value","adapter_identifier","adapter_version","transport","source_payload","ingestion_metadata"])assert.match(service,new RegExp(field));for(const forbidden of ["lema.signals","daily_sessions","waist_measurements"])assert.doesNotMatch(service,new RegExp(forbidden));});
test("device registration is idempotent and preserves canonical device identity",()=>{const service=read("server/src/textile-lab/textile-lab.service.ts");assert.match(service,/ON CONFLICT\(device_identifier\) DO UPDATE/);assert.match(service,/updated_by=EXCLUDED\.updated_by/);assert.doesNotMatch(service,/created_by=EXCLUDED\.created_by/);});
test("account population and activity purpose remain separate and traction is opt-in",()=>{const migration=read("server/sql/20260813_textile_intelligence_lab_phase1.sql"),founder=read("server/src/routes/founder.ts"),summary=read("server/src/routes/summary.routes.ts");for(const population of ["founder_experiment","controlled_test","real_world_test","genuine_beta"])assert.match(migration,new RegExp(population));for(const purpose of ["engineering","calibration","controlled_test","real_world_wear","genuine_product_use"])assert.match(migration,new RegExp(purpose));assert.match(migration,/analytics_population_snapshot/);assert.match(migration,/analytics_eligible boolean NOT NULL DEFAULT false/);assert.doesNotMatch(migration,/@gmail|@live/i);assert.ok((founder.match(/analytics_eligible=true/g)??[]).length>=5);assert.ok((summary.match(/analytics_eligible=true/g)??[]).length>=2);});
test("local founder cookies remain secure-by-environment without weakening Lab authorization",()=>{const auth=read("server/src/services/data-room.service.ts"),routes=read("server/src/textile-lab/textile-lab.routes.ts");assert.match(auth,/secure \? "SameSite=None" : "SameSite=Lax"/);assert.match(auth,/if \(secure\) cookieParts\.push\("Secure"\)/);assert.match(routes,/router\.use\(requireDataRoomAuth,requireAdmin\)/);});
test("calibration foundation has versioned lineage, immutable history and locked user-facing state",()=>{const sql=read("server/sql/20260814_textile_lab_calibration_foundation.sql");for(const table of ["adapter_definitions","channels","experiment_protocols","calibration_runs","reference_observations","algorithm_versions","derived_results","result_reviews"])assert.match(sql,new RegExp(`CREATE TABLE textile_lab\\.${table}`));assert.match(sql,/calibration history is append-only/);assert.match(sql,/USER_FACING is locked/);assert.match(sql,/validate_calibration_run_links/);assert.match(sql,/supersedes_result_id/);});
test("calibration metrics remain physical-signal statistics without health inference",()=>{const metrics=calculateCalibrationMetrics([{value:100,phase:"baseline",referenceValue:0,cycleNumber:1},{value:102,phase:"baseline",referenceValue:0,cycleNumber:2},{value:120,phase:"load",referenceValue:10,cycleNumber:1},{value:118,phase:"unload",referenceValue:10,cycleNumber:1},{value:101,phase:"recovery",referenceValue:0,cycleNumber:1}],5);assert.equal(metrics.baseline_mean,101);assert.equal(metrics.signal_completeness,100);assert.equal(metrics.hysteresis_indicator,2);assert.ok(!("bloating" in metrics));});
test("engineering metrics endpoint is aggregate-only and never joins participant identity",()=>{const service=read("server/src/textile-lab/textile-lab.service.ts");const query=service.slice(service.indexOf("export async function engineeringMetrics"));assert.match(query,/raw_observations/);assert.doesNotMatch(query,/lema\.user_profiles|participants|email|raw_value/);});
